all : 	./cleandirs.sh .; echo "calling cleandirs"
	python nave_interface.py

debug: ./cleandirs.sh .; echo "calling cleandirs"
	python nave_interface.py 0

clean: ./cleandirs.sh .; echo "cleaning dirs"
	rm *.pyc *.py~ ; echo "cleaning *cs and *~s"
